# Generated by Django 5.2.1 on 2025-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fats_per_100g_ingredient_fat_per_100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='usda_food_portions',
            field=models.JSONField(blank=True, help_text='Raw foodPortions array from USDA API, used for unit conversions', null=True),
        ),
    ]
