# Generated by Django 5.2.1 on 2025-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingredient_usda_food_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fdc_id',
            field=models.IntegerField(blank=True, help_text='FoodData Central ID from USDA', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
